export const IPAD = "iPad";
export const APPLE_WATCH = "Apple Watch";
export const ALL_PART_NUMBERS = {
  [IPAD]: [
    // 11"
    'MTXP2ZP/A',
    'MTXR2ZP/A',
    'MTXU2ZP/A',
    'MTXW2ZP/A',
    'MU222ZP/A',
    'MU1M2ZP/A',
    'MU172ZP/A',
    'MU0U2ZP/A',
    'MTXN2ZP/A',
    'MTXQ2ZP/A',
    'MTXT2ZP/A',
    'MTXV2ZP/A',
    'MU1V2ZP/A',
    'MU1F2ZP/A',
    'MU102ZP/A',
    'MU0M2ZP/A',
    // 12.9"
    'MTEM2ZP/A',
    'MTFN2ZP/A',
    'MTFQ2ZP/A',
    'MTFT2ZP/A',
    'MTJV2ZP/A',
    'MTJJ2ZP/A',
    'MTHP2ZP/A',
    'MTJ62ZP/A',
    'MTEL2ZP/A',
    'MTFL2ZP/A',
    'MTFP2ZP/A',
    'MTFR2ZP/A',
    'MTJP2ZP/A',
    'MTJD2ZP/A',
    'MTHV2ZP/A',
    'MTHJ2ZP/A',
  ],
  [APPLE_WATCH]: [
    'MU642ZP/A',
    'MU6A2ZP/A',
    'MTVR2ZP/A',
    'MTVA2ZP/A',
    'MU682ZP/A',
    'MTVG2ZP/A',
    'MTVW2ZP/A',
    'MU6F2ZP/A',
    'MU662ZP/A',
    'MTVD2ZP/A',
    'MTVU2ZP/A',
    'MU6D2ZP/A',
    'MU652ZP/A',
    'MU6C2ZP/A',
    'MTVT2ZP/A',
    'MTVC2ZP/A',
    'MU692ZP/A',
    'MU6G2ZP/A',
    'MTVX2ZP/A',
    'MTVH2ZP/A',
    'MU672ZP/A',
    'MTVF2ZP/A',
    'MTVV2ZP/A',
    'MU6E2ZP/A',
  
    'MTVJ2ZP/A',
    'MTX02ZP/A',
    'MTVN2ZP/A',
    'MTX42ZP/A',
    'MTX22ZP/A',
    'MTVL2ZP/A',
    'MTVK2ZP/A',
    'MTX12ZP/A',
    'MTVQ2ZP/A',
    'MTX52ZP/A',
    'MTVM2ZP/A',
    'MTX32ZP/A',
  
    // Nike+
    'MU6H2ZP/A',
    'MU6K2ZP/A',
    'MTXK2ZP/A',
    'MTX62ZP/A',
    'MU6J2ZP/A',
    'MU6L2ZP/A',
    'MTXM2ZP/A',
    'MTXG2ZP/A',
    'MU7F2ZP/A',
    'MTXF2ZP/A',
    'MTXJ2ZP/A',
    'MU7H2ZP/A',
    'MU7G2ZP/A',
    'MU7J2ZP/A',
    'MTXL2ZP/A',
    'MTXH2ZP/A',
  
    //hermēs'
    'MU7L2ZP/A',
    'MU732ZP/A',
    'MU782ZP/A',
    'MU702ZP/A',
    'MU722ZP/A',
    'MU712ZP/A',
    'MU772ZP/A',
    'MU6Y2ZP/A',
    'MU762ZP/A',
    'MU9E2ZP/A',
    'MU752ZP/A',
    'MU742ZP/A',
  ]
}


